/**
 * GitHub Gist Integration
 * Upload contract code to GitHub Gist for Solana Playground import
 */

export interface GistFile {
  content: string;
}

export interface GistData {
  description: string;
  public: boolean;
  files: Record<string, GistFile>;
}

export interface GistResponse {
  id: string;
  html_url: string;
  files: Record<string, { raw_url: string }>;
}

/**
 * Create a GitHub Gist with contract code
 */
export async function createContractGist(
  contractCode: string,
  programName: string,
  cargoToml?: string
): Promise<GistResponse> {
  const githubToken = process.env.NEXT_PUBLIC_GITHUB_TOKEN;
  
  if (!githubToken) {
    throw new Error('GitHub token not configured. Please set NEXT_PUBLIC_GITHUB_TOKEN in .env.local');
  }

  const files: Record<string, GistFile> = {
    'lib.rs': {
      content: contractCode,
    },
  };

  // Add Cargo.toml if provided
  if (cargoToml) {
    files['Cargo.toml'] = {
      content: cargoToml,
    };
  }

  // Add README with instructions
  files['README.md'] = {
    content: `# ${programName}

Generated by AssetRail Smart Contract Generator

## How to use in Solana Playground

1. Go to https://beta.solpg.io/
2. Create new Anchor project
3. Import this Gist
4. Build and deploy!

## Files

- \`lib.rs\` - Main contract code
${cargoToml ? '- `Cargo.toml` - Project dependencies' : ''}

---

Generated at ${new Date().toISOString()}
`,
  };

  const gistData: GistData = {
    description: `${programName} - AssetRail Smart Contract`,
    public: true,
    files,
  };

  try {
    const response = await fetch('https://api.github.com/gists', {
      method: 'POST',
      headers: {
        'Accept': 'application/vnd.github+json',
        'Authorization': `Bearer ${githubToken}`,
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(gistData),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ message: 'Unknown error' }));
      throw new Error(`GitHub API error: ${response.status} - ${error.message}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Failed to create Gist:', error);
    throw error;
  }
}

/**
 * Open Solana Playground with GitHub Gist
 * 
 * This copies the Gist URL to clipboard and shows clear import instructions
 */
export function openPlaygroundWithGist(gistUrl: string, programName: string): void {
  // Copy URL to clipboard immediately
  navigator.clipboard.writeText(gistUrl).catch(() => {
    console.warn('Could not copy to clipboard');
  });
  
  // Open Solana Playground in new tab
  const playgroundWindow = window.open('https://beta.solpg.io/', '_blank');
  
  // Show instructions with Gist URL
  setTimeout(() => {
    const instructions = `
✅ Gist URL copied to clipboard!

Your contract: ${gistUrl}

TO IMPORT INTO SOLANA PLAYGROUND:

1. In the Playground tab that just opened:
   - Click "Import" (top right)
   - Select "From GitHub"
   - Paste the Gist URL (already copied!)
   - Click "Import"

2. Alternative (if Import menu is different):
   - Look for file import options
   - Paste: ${gistUrl}

3. If that doesn't work, download the files from:
   ${gistUrl}

Click OK to continue.
    `.trim();
    
    alert(instructions);
  }, 1000);
}

/**
 * Check if GitHub token is configured
 */
export function isGitHubTokenConfigured(): boolean {
  return !!process.env.NEXT_PUBLIC_GITHUB_TOKEN;
}

