/**
 * Solana Playground Integration Utilities
 */

export interface PlaygroundProject {
  files: Record<string, string>;
  name?: string;
}

/**
 * Open contract in Solana Playground
 */
export function openInSolanaPlayground(code: string, programName: string = 'contract'): void {
  try {
    // Try multiple methods to load code into Playground
    
    // Method 1: Try URL with base64 encoded project (may have size limits)
    const projectData = {
      files: {
        'src/lib.rs': code,
        'Cargo.toml': generateCargoToml(programName),
      },
      name: programName,
    };
    
    try {
      const encoded = btoa(JSON.stringify(projectData));
      // Try opening with encoded project (experimental)
      const playgroundUrl = `https://beta.solpg.io/?code=${encoded}`;
      
      // Check if URL is reasonable length (< 2000 chars)
      if (playgroundUrl.length < 2000) {
        window.open(playgroundUrl, '_blank');
        console.log('Opened Playground with encoded project');
        return;
      }
    } catch (encodeError) {
      console.warn('Could not encode project for URL:', encodeError);
    }
    
    // Method 2: Just open Playground (fallback)
    window.open('https://beta.solpg.io/', '_blank');
    
    // Show instructions after a brief delay
    setTimeout(() => {
      showPlaygroundInstructions(programName);
    }, 500);
  } catch (error) {
    console.error('Error opening Solana Playground:', error);
    alert('Failed to open Solana Playground. Please visit https://beta.solpg.io/ directly.');
  }
}

/**
 * Show instructions for importing contract into Playground
 */
function showPlaygroundInstructions(programName: string): void {
  const instructions = `
🚀 Solana Playground opened in a new tab!

To use your generated contract:

1. In Solana Playground, click "New Project" → "Anchor"
2. Click "Import" and upload your downloaded ZIP
3. The contract code will be automatically loaded
4. Click "Build" to compile
5. Connect your wallet (Playground Wallet or Phantom)
6. Click "Deploy" to deploy to devnet
7. Copy the Program ID for your records

Need help? Check the Solana Playground docs or AssetRail documentation.
  `.trim();
  
  // Show modal (you can create a custom modal component later)
  if (confirm(instructions + '\n\nWould you like to download the contract ZIP now?')) {
    // Trigger download (handled by the calling component)
    return;
  }
}

/**
 * Create Playground URL with encoded project (experimental)
 */
export function createPlaygroundUrl(project: PlaygroundProject): string {
  try {
    // Encode project data
    const encoded = btoa(JSON.stringify(project));
    
    // Note: This may not work due to URL length limits
    // Solana Playground may not support this parameter
    return `https://beta.solpg.io/?code=${encoded}`;
  } catch (error) {
    console.error('Error creating Playground URL:', error);
    return 'https://beta.solpg.io/';
  }
}

/**
 * Generate Cargo.toml for Rust/Anchor projects
 */
export function generateCargoToml(programName: string): string {
  return `[package]
name = "${programName.replace(/_/g, '-')}"
version = "0.1.0"
description = "Generated by AssetRail Contract Generator"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "${programName}"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

[dev-dependencies]
solana-program-test = "~1.16"
solana-sdk = "~1.16"
spl-token = { version = "4.0", features = ["no-entrypoint"] }
`;
}

/**
 * Generate basic test file
 */
export function generateTestFile(programName: string): string {
  return `import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { ${toPascalCase(programName)} } from "../target/types/${programName}";

describe("${programName}", () => {
  // Configure the client to use the local cluster
  anchor.setProvider(anchor.AnchorProvider.env());

  const program = anchor.workspace.${toPascalCase(programName)} as Program<${toPascalCase(programName)}>;

  it("Program deploys successfully", async () => {
    console.log("Program ID:", program.programId.toBase58());
    // Add your tests here
  });
});
`;
}

/**
 * Convert snake_case to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Download ZIP file
 */
export function downloadZip(zipBlob: Blob, filename: string = 'contract.zip'): void {
  try {
    const url = URL.createObjectURL(zipBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error downloading ZIP:', error);
    alert('Failed to download ZIP file. Please try again.');
  }
}

